@startuml
!include <office/Concepts/globe_internet>
!include <office/Concepts/documents>
!include <office/Users/user>
!include style.puml

Package " "<<Rectangle>>{
    Class Commons LOGIC_COLOR_T2
    Package "Layer 3"<<Rectangle>>{
        note "**Multi-Layered Architecture**\nEach layer can only interact with lower layers" as N
        Class Main #grey
    }

    Package "Layer 2"<<Rectangle>>{
        Class UI UI_COLOR
    }
    Package "Layer 1"<<Rectangle>>{
        Class Logic LOGIC_COLOR
    }
    Package "Layer 0"<<Rectangle>>{
        Class Storage STORAGE_COLOR
        Class Model MODEL_COLOR
    }
}


Class "<$user>" as User MODEL_COLOR_T2
Class "<$documents>" as File UI_COLOR_T1


Main -[#grey]-> UI
UI -[#green]> Logic
UI ---[#green]-> Model
Main --down[#grey]-> Logic
Main -[#grey]-> Storage
Main -[#grey]-> Model
Logic -left[#blue]-> Storage
Logic -down[#blue]-> Model

Storage .left[STORAGE_COLOR].>File
User ..> UI
@enduml
