@startuml
!include <office/Concepts/globe_internet>
!include <office/Concepts/documents>
!include <office/Users/user>
!include style.puml

Package " "<<Rectangle>>{
    note "**Multi-Layered Architecture**\nEach layer can only interact with lower layers" as N
    Class Commons LOGIC_COLOR_T2
    Class Main #grey
    Class UI UI_COLOR
    Class Logic LOGIC_COLOR
    Class Storage STORAGE_COLOR
    Class Model MODEL_COLOR
}


Class "<$user>" as User MODEL_COLOR_T2
Class "<$documents>" as File UI_COLOR_T1


Main -[#grey]-> UI
UI -[#green]> Logic
UI --[#green]-> Model
Main --down[#grey]-> Logic
Main -[#grey]-> Storage
Main -[#grey]-> Model
Logic -down[#blue]-> Storage
Logic -down[#blue]-> Model

Storage .left[STORAGE_COLOR].>File
User ..> UI
@enduml
