@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":MainParser" as MainParser LOGIC_COLOR
participant ":DeleteCommandParser" as DeleteCommandParser LOGIC_COLOR
participant ":DeleteApplicationCommandParser" as DeleteApplicationCommandParser LOGIC_COLOR
participant "d:DeleteApplicationCommand" as DeleteApplicationCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("delete app 1")
activate LogicManager

LogicManager -> MainParser : parseCommand("delete app 1")
activate MainParser

create DeleteCommandParser
MainParser -> DeleteCommandParser
activate DeleteCommandParser

DeleteCommandParser --> MainParser
deactivate DeleteCommandParser

MainParser -> DeleteCommandParser : parse("app 1")
activate DeleteCommandParser

create DeleteApplicationCommandParser
DeleteCommandParser -> DeleteApplicationCommandParser
activate DeleteApplicationCommandParser

DeleteApplicationCommandParser --> DeleteCommandParser
deactivate DeleteApplicationCommandParser

DeleteCommandParser -> DeleteApplicationCommandParser : parse("1")
activate DeleteApplicationCommandParser

create DeleteApplicationCommand
DeleteApplicationCommandParser -> DeleteApplicationCommand : DeleteApplicationCommand(1)
activate DeleteApplicationCommand

DeleteApplicationCommand --> DeleteApplicationCommandParser : d
deactivate DeleteApplicationCommand

DeleteApplicationCommandParser --> DeleteCommandParser : d
deactivate DeleteApplicationCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteApplicationCommandParser -[hidden]-> DeleteCommandParser
destroy DeleteApplicationCommandParser

DeleteCommandParser --> MainParser : d
deactivate DeleteCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteCommandParser -[hidden]-> MainParser
destroy DeleteCommandParser

MainParser --> LogicManager : d
deactivate MainParser

LogicManager -> DeleteApplicationCommand : execute(model)
activate DeleteApplicationCommand

DeleteApplicationCommand -> Model : deleteApplication(1)
activate Model

Model --> DeleteApplicationCommand
deactivate Model

create CommandResult
DeleteApplicationCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteApplicationCommand : result
deactivate CommandResult

DeleteApplicationCommand --> LogicManager : result
deactivate DeleteApplicationCommand

[<--LogicManager
deactivate LogicManager
@enduml
