@startuml
!include InternHunterStyle.puml
!$index = 1
!$profileItemToEdit = "profileItemToEdit"

box Logic LOGIC_COLOR_T1
participant ":EditProfileCommand" as EditProfileCommand LOGIC_COLOR
participant ":CommandUtil" as CommandUtil LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant "profileList:ItemListManager" as ItemListManager MODEL_COLOR
end box

mainframe sd execute edit me command

[-> EditProfileCommand: execute(model)
activate EditProfileCommand

EditProfileCommand -> CommandUtil : getProfileItem(model, $index)
activate CommandUtil


CommandUtil -> Model : getFilteredProfileList()
activate Model

Model -> ItemListManager : getFilteredItemList()
activate ItemListManager

ItemListManager --> Model : lastShownList
deactivate ItemListManager

Model --> CommandUtil : lastShownList
deactivate Model


CommandUtil -> ItemListManager : getItemFromFilteredList($index)
activate ItemListManager

ItemListManager --> CommandUtil: $profileItemToEdit
deactivate ItemListManager


CommandUtil --> EditProfileCommand : $profileItemToEdit
deactivate CommandUtil


'EditProfileCommand -> EditProfileCommand: createEditedProfileItem(toEdit, editProfileItemDescriptor)
'activate EditProfileCommand
'EditProfileCommand --> EditProfileCommand : editedProfileItem
'deactivate EditProfileCommand

EditProfileCommand -> Model : getProfileList()
activate Model


Model --> EditProfileCommand
deactivate Model

EditProfileCommand -> ItemListManager : setItem(profileItemToEdit, editedProfileItem)
activate ItemListManager

ItemListManager --> EditProfileCommand
deactivate ItemListManager

[<-- EditProfileCommand: commandResult
deactivate EditProfileCommand
@enduml
