@startuml
!include InternHunterStyle.puml
skinparam arrowThickness 1
skinparam arrowColor STORAGE_COLOR_T2
skinparam classBackgroundColor STORAGE_COLOR
skinparam classAttributeFontColor #FFFFFF

hide members

class "ABSTRACT\nJsonAdaptedItem" as JsonAdaptedItem {
    +toModelType(): Item
}

Class JsonAdaptedApplicationItem
Class JsonAdaptedCompanyItem
Class JsonAdaptedInternshipItem
Class JsonAdaptedProfileItem

show JsonAdaptedItem methods

JsonAdaptedApplicationItem -u-|> JsonAdaptedItem
JsonAdaptedCompanyItem -u-|> JsonAdaptedItem
JsonAdaptedInternshipItem -u-|> JsonAdaptedItem
JsonAdaptedProfileItem -u-|> JsonAdaptedItem

@enduml
