@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface Model <<Interface>>
Interface ObservableList <<Interface>>
Interface ReadOnlyUserPrefs <<Interface>>

Class Model
Class ModelManager
Class ObservableList
Class UserPrefs
Class ReadOnlyUserPrefs

Package View {
Interface View <<Interface>>
Class View
}

Package Tab {
Interface Tab <<Interface>>
Class Tab
}

Package Item {
Class "{abstract}\nItem" as Item
}

Package Company\n {
Class CompanyItem
}

Package Internship\n {
Class InternshipItem
}

Package Application\n {
Class ApplicationItem
}

Package Profile\n {
Class ProfileItem
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

Model .left.> ReadOnlyUserPrefs
ModelManager .up.|> Model
Model .right.> ObservableList
ModelManager -left-> "1" UserPrefs
ModelManager -right-> Tab
ModelManager -right-> View
UserPrefs .up.|> ReadOnlyUserPrefs

CompanyItem --|> Item
ApplicationItem --|> Item
ProfileItem --|> Item
InternshipItem -right-|> Item

ModelManager --> "*" CompanyItem : has filterable item list of >
ModelManager --> "*" ApplicationItem : has filterable item list of >
ModelManager --> "*" ProfileItem : has filterable item list of >
CompanyItem --> "*" InternshipItem
ApplicationItem --> "1" InternshipItem
@enduml
