@startuml
(*)  --> If "" then
    [applicationItemList.json is empty] If "" then
        [companyItemList.json is empty] If "" then
        ---> [profileItemList.json is empty] "use sample data"
        -->(*)
        else
        --> [else] "use user data"
        Endif
    else
    --> [else] "use user data"
    Endif
else
--> [else] "use user data"
Endif
-->(*)
@enduml
