@startuml
!include style.puml
skinparam arrowThickness 1
skinparam arrowColor STORAGE_COLOR_T2
skinparam classBackgroundColor STORAGE_COLOR
skinparam genericDisplay old

Interface Storage <<Interface>>
Interface UserPrefsStorage <<Interface>>
Interface ItemListStorage<? extends Item,? extends JsonAdaptedItem> <<Interface>>

Class StorageManager
Class JsonUserPrefsStorage
Class JsonItemListStorage<? extends Item,? extends JsonAdaptedItem>

StorageManager .left.|> Storage
StorageManager o-right-> UserPrefsStorage
StorageManager o--> ItemListStorage

Class JsonSerializableItemList<? extends JsonAdaptedItem>
abstract JsonAdaptedItem

JsonUserPrefsStorage .left.|> UserPrefsStorage
JsonItemListStorage .u.|> ItemListStorage
JsonItemListStorage .r.> JsonSerializableItemList
JsonSerializableItemList .u.> JsonAdaptedItem
@enduml
