@startuml
!include InternHunterStyle.puml

skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>> {
Interface Ui <<Interface>>
Class "{abstract}\nUiPart" as UiPart
Class UiManager
Class MainWindow
Class HelpWindow
Class InternshipWindow
Class PopupWindow
Class Tabs
Class CommandBox
Class ResultDisplay

Class "{abstract}\nCard" as Card
Class InformationDisplay
Class ListPanel

Class CompanyCard
Class ApplicationCard
Class ProfileCard

Class CompanyDisplay
Class ApplicationDisplay
Class ProfileDisplay

Class ApplicationListPanel
Class CompanyListPanel
Class ProfileListPanel

}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}
UI -down[hidden]-> Model
package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui

UiManager .left.|> Ui
UiManager -up-> Logic
UiManager --> MainWindow

MainWindow -up-> Logic
MainWindow *-right-> ListPanel
MainWindow *-left-> InformationDisplay
MainWindow *--> ResultDisplay
MainWindow *--> CommandBox
MainWindow *--> Tabs
MainWindow --> HelpWindow
MainWindow --> InternshipWindow

ApplicationDisplay -left-|> InformationDisplay
CompanyDisplay -left-|> InformationDisplay
ProfileDisplay -left-|> InformationDisplay


ApplicationListPanel -left-|> ListPanel
CompanyListPanel -left-|> ListPanel
ProfileListPanel -left-|> ListPanel

ApplicationListPanel *--> ApplicationCard
CompanyListPanel *--> CompanyCard
ProfileListPanel *--> ProfileCard

ApplicationCard --|> Card
CompanyCard --|> Card
ProfileCard --|> Card

HelpWindow --|> PopupWindow
InternshipWindow --|> PopupWindow

Card -down-|> UiPart
PopupWindow -down-|> UiPart
ResultDisplay -down-|> UiPart
MainWindow -down-|> UiPart
CommandBox -down-|> UiPart
Tabs -down-|> UiPart
InformationDisplay -down-|> UiPart


ApplicationCard ..>Model
ProfileCard ..> Model
CompanyCard ..> Model
ApplicationDisplay ..> Model
CompanyDisplay ..> Model
ProfileDisplay ..> Model
UiPart .[hidden].> Model

@enduml